title: AI Blog
description: Exploring the frontiers of artificial intelligence, machine learning, and emerging technologies.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

# SEO and Social Media
author: Your Name
twitter:
  username: your_twitter_handle
  card: summary_large_image
social:
  name: Your Name
  links:
    - https://twitter.com/your_twitter_handle
    - https://github.com/rwadalebsar

# Site settings
lang: en-US
timezone: UTC
permalink: /:year/:month/:day/:title/

# Multi-language support
languages: ["en", "ar"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "assets"]

# Arabic/RTL specific settings
rtl_support: true
arabic_font: "Almarai, Rubik, IBM Plex Sans Arabic, sans-serif"
css_version: "v2.1" # For cache busting

# Language-specific titles and descriptions
title_en: "AI Blog"
title_ar: "مدونة الذكاء الاصطناعي"
description_en: "Exploring the frontiers of artificial intelligence, machine learning, and emerging technologies."
description_ar: "استكشاف آفاق الذكاء الاصطناعي والتعلم الآلي والتقنيات الناشئة."

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script/
  - docs/